In [68]:
import pandas as pd
import pickle
import matplotlib.pyplot as plt

In [69]:
df = pd.read_pickle(r"C:\Users\adamk\Desktop\Digitální akademie DATA\Projekt\joined_data\cdr_clean_unique_calls_update_num.pkl")

In [82]:
#df.sort_values("unique_call_id").head()
df.head()

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus,unique_call_id
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,HK010_CC,12,0,0,0,0,0,0,0,752520
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,HK010_CC,12,0,0,0,0,0,0,0,752521
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,HK010_CC,12,0,0,0,0,0,0,0,752522
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,HK010_CC,12,0,0,0,0,0,0,0,752523
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,HK010_CC,0,12,0,0,0,0,0,0,752524

In [105]:
date_columns=[column for column in df.columns if "date" in column.lower()]
number_columns=[column for column in df.columns if "number" in column.lower()]
print(date_columns)
print(number_columns)

cols=date_columns+number_columns+["unique_call_id"]
cols

['dateTimeOrigination', 'dateTimeConnect', 'dateTimeDisconnect']
['callingPartyNumber', 'originalCalledPartyNumber', 'finalCalledPartyNumber']

['dateTimeOrigination',
 'dateTimeConnect',
 'dateTimeDisconnect',
 'callingPartyNumber',
 'originalCalledPartyNumber',
 'finalCalledPartyNumber',
 'unique_call_id']

In [106]:
df[cols]

,dateTimeOrigination,dateTimeConnect,dateTimeDisconnect,callingPartyNumber,originalCalledPartyNumber,finalCalledPartyNumber,unique_call_id
0,2024-01-01 01:20:13,2024-01-01 01:20:14,2024-01-01 01:20:22,437734693017,4344124999,4344124999,752520
1,2024-01-01 03:08:00,2024-01-01 03:08:02,2024-01-01 03:08:14,436618449646,433738509500050,433738509500050,752521
2,2024-01-01 05:07:47,NaT,2024-01-01 05:07:47,436359992566,433738509500050,433738509500050,752522
3,2024-01-01 05:41:29,2024-01-01 05:41:31,2024-01-01 05:42:05,9999,4314014190122,4314014190122,752523
4,2024-01-01 06:07:14,2024-01-01 06:07:15,2024-01-01 06:07:50,433496903750,4373935601800,4373935601800,752524
...,...,...,...,...,...,...,...
3805581,2024-03-29 19:15:54,2024-03-29 19:15:54,2024-03-29 19:16:39,43204838804831,43204838804829,5058900,2781782
3805582,2024-03-30 15:12:29,2024-03-30 15:12:42,2024-03-30 15:29:03,434005336339264,50335447441930,50335447441930,2781783
3805583,2024-03-30 15:34:07,2024-03-30 15:34:31,2024-03-30 16:06:17,434005336339264,50335447441930,50335447441930,2781784
3805584,2024-03-30 18:13:14,2024-03-30 18:13:31,2024-03-30 18:14:02,432537661412,2868767180,2868767180,2781785
3805585,2024-03-31 10:04:59,NaT,2024-03-31 10:05:15,434424270388476,92854133396,92854133396,2781786

In [81]:
df[df.unique_call_id==0]

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus,unique_call_id
222972,1,1,20554141,2024-01-16 10:11:47,4369121193063,393216,20554142,4321454093284,4321454093284,393216,...,CSFC38K6092,17,17,0,0,0,0,0,0,0
223266,1,1,20554142,2024-01-16 10:11:52,4321454093284,16,20554096,4369121193063,4369121193063,0,...,BK053_000_Tele2,12,17,0,18,0,146,18,0,0

In [83]:
df["unique_call_id"].describe().round(0)

count    3262835.0
mean     1295763.0
std       808556.0
min            0.0
25%       584974.0
50%      1241002.0
75%      1991282.0
max      2781786.0
Name: unique_call_id, dtype: float64

In [84]:
df.dtypes

globalCallID_callManagerId                    int64
globalCallID_callId                           int64
origLegCallIdentifier                         int64
dateTimeOrigination                  datetime64[ns]
callingPartyNumber                           object
origCause_value                               int64
destLegIdentifier                             int64
originalCalledPartyNumber                    object
finalCalledPartyNumber                       object
destCause_value                               int64
dateTimeConnect                      datetime64[ns]
dateTimeDisconnect                   datetime64[ns]
lastRedirectDn                       string[python]
pkid                                 string[python]
duration                                      int64
origDeviceName                       string[python]
destDeviceName                       string[python]
origCallTerminationOnBehalfOf                 int64
destCallTerminationOnBehalfOf                 int64
origCalledPartyRedirectOnBehalfOf             int64
lastRedirectRedirectOnBehalfOf                int64
origCalledPartyRedirectReason                 int64
lastRedirectRedirectReason                    int64
joinOnBehalfOf                                int64
callSecuredStatus                             int64
unique_call_id                                int64
dtype: object

In [85]:
df["unique_call_id"].head(100)

0     752520
1     752521
2     752522
3     752523
4     752524
       ...
95    752610
96    752611
97    752612
98    752613
99    752614
Name: unique_call_id, Length: 100, dtype: int64

In [111]:
df[cols]

,dateTimeOrigination,dateTimeConnect,dateTimeDisconnect,callingPartyNumber,originalCalledPartyNumber,finalCalledPartyNumber,unique_call_id
0,2024-01-01 01:20:13,2024-01-01 01:20:14,2024-01-01 01:20:22,437734693017,4344124999,4344124999,752520
1,2024-01-01 03:08:00,2024-01-01 03:08:02,2024-01-01 03:08:14,436618449646,433738509500050,433738509500050,752521
2,2024-01-01 05:07:47,NaT,2024-01-01 05:07:47,436359992566,433738509500050,433738509500050,752522
3,2024-01-01 05:41:29,2024-01-01 05:41:31,2024-01-01 05:42:05,9999,4314014190122,4314014190122,752523
4,2024-01-01 06:07:14,2024-01-01 06:07:15,2024-01-01 06:07:50,433496903750,4373935601800,4373935601800,752524
...,...,...,...,...,...,...,...
3805581,2024-03-29 19:15:54,2024-03-29 19:15:54,2024-03-29 19:16:39,43204838804831,43204838804829,5058900,2781782
3805582,2024-03-30 15:12:29,2024-03-30 15:12:42,2024-03-30 15:29:03,434005336339264,50335447441930,50335447441930,2781783
3805583,2024-03-30 15:34:07,2024-03-30 15:34:31,2024-03-30 16:06:17,434005336339264,50335447441930,50335447441930,2781784
3805584,2024-03-30 18:13:14,2024-03-30 18:13:31,2024-03-30 18:14:02,432537661412,2868767180,2868767180,2781785
3805585,2024-03-31 10:04:59,NaT,2024-03-31 10:05:15,434424270388476,92854133396,92854133396,2781786

In [125]:
group=df[df.unique_call_id==0].sort_values("dateTimeConnect")["callingPartyNumber"].iloc[0]
group

'4369121193063'

In [137]:
# Top 10 volajících (callingPartyNumber) podle počtu hovorů
# pro každý sloupec unique call id chci vybrat řádek s nejmenším sloupcem datetimeconnect

groups= df.groupby("unique_call_id")

# TODO: handle missing data
def number_first_call(group):
    return group.sort_values("dateTimeConnect")["callingPartyNumber"].iloc[0] #vrací první řádek

def number_first_call_fast(group):
    """Faster, because argmin is faster than sort"""
    group=group.dropna(subset=["dateTimeConnect"])
    if len(group)==0:
        return None
    else:
        return group.callingPartyNumber.iloc[group.dateTimeConnect.argmin()]

unique_calls = groups.apply(number_first_call_fast)

call_counts = unique_calls.value_counts()

top10 = call_counts.head(10)
print(f"Top 10 volajících podle počtu unikátních hovorů: {top10}")

KeyboardInterrupt:

In [ ]:
# kam nejčastěji volá číslo, které má nejvíce odchozích hovorů
top_caller = "+4348751591592"
top_caller_calls = unique_calls_df[unique_calls_df['callingPartyNumber'] == top_caller]

top_called = top_caller_calls['finalCalledPartyNumber'].value_counts().head(5)
print(f"Top 5 volaná čísla TOP 1 volajícího ({top_caller})")
print(top_called)

In [ ]:
# Top 10 volaných (finalCalledPartyNumber) podle počtu hovorů
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])

call_counts = unique_calls_df["finalCalledPartyNumber"].value_counts()

top10 = call_counts.head(10)
print(f"Top 10 volaných podle počtu unikátních hovorů: {top10}")

In [ ]:
# Poměr přijatých vs. zmeškaných hovorů - dateTimeConnect > 0 = přijatý, 0 = zmeškaný
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])

prijaté = unique_calls_df[pd.notna(unique_calls_df['dateTimeConnect'])]
pocet_prijatych = len(prijaté)

zmeskane = unique_calls_df[pd.isna(unique_calls_df['dateTimeConnect'])]

zmeskane = zmeskane[pd.notna(zmeskane['dateTimeDisconnect'])]
pocet_zmeskanych = len(zmeskane)

celkem = pocet_prijatych + pocet_zmeskanych
procento_prijatych = pocet_prijatych / celkem * 100
procento_zmeskanych = pocet_zmeskanych / celkem * 100

print(f"Přijaté hovory: {pocet_prijatych}({procento_prijatych:.2f}%)")
print(f"Zmeškané hovory: {pocet_zmeskanych}({procento_zmeskanych:.2f}%)")

In [ ]:
# Podíl zabezpečených hovorů (callSecuredStatus) - kolik bylo šifrovaných, kolik nezabezpečených.
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])

non_secured = 0
not_encrypted = 0
encrypted = 0

for status in unique_calls_df['callSecuredStatus']:
    if pd.notna(status):
        if status == 0:
            non_secured += 1
        elif status == 1:
            not_encrypted += 1
        elif status == 2:
            encrypted += 1

total = non_secured + not_encrypted + encrypted

print(f"Non secured: {non_secured}")
print(f"Not encrypted: {not_encrypted}")
print(f"Encrypted: {encrypted}")

In [ ]:
# délka hovoru  - první řádek odtrsnit, nebo jiný řádek odstranit? connect - dissconect
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])
print("Statistické shrnutí sloupce 'duration':")
unique_calls_df["duration"].describe().round(0)

In [ ]:
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])


durations = unique_calls_df['duration']


over_100 = len(durations[durations > 100])
over_1000 = len(durations[durations > 1000])
over_10000 = len(durations[durations > 10000])
over_6h = len(durations[durations > 21600])
over_43000 = len(durations[durations > 43000])

print(f"Hovory delší než 100 s:{over_100}")
print(f"Hovory delší než 1 000 s:{over_1000}")
print(f"Hovory delší než 10 000 s:{over_10000}")
print(f"Hovory delší než 6 hodin:{over_6h}")
print(f"Hovory delší než 43 000 s:{over_43000}")

median_duration = unique_calls_df['duration'].median()
print(f"Medián délky hovoru: {median_duration} sekund")

In [ ]:
with pd.option_context('display.max_rows', 5, 'display.max_columns', None): 
    display(df.head(1000))

In [ ]:
# Kolik hovorů v lednu, únoru a březnu
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])

hovory_leden = 0
hovory_unor = 0
hovory_brezen = 0

# projít všechny hovory
for date in unique_calls_df['dateTimeOrigination']:
    if pd.notna(date):  
        if pd.Timestamp('2024-01-01') <= date <= pd.Timestamp('2024-01-31 23:59:59'):
            hovory_leden += 1
        elif pd.Timestamp('2024-02-01') <= date <= pd.Timestamp('2024-02-29 23:59:59'):
            hovory_unor += 1
        elif pd.Timestamp('2024-03-01') <= date <= pd.Timestamp('2024-03-31 23:59:59'):
            hovory_brezen += 1

print(f"Hovory v lednu: {hovory_leden}")
print(f"Hovory v únoru: {hovory_unor}")
print(f"Hovory v březnu: {hovory_brezen}")

In [ ]:
# Průměrný počet hovorů rozdělených na dny (Po - Ne) za poslední čtvrtletí
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])
dni = {'Po':0, 'Út':0, 'St':0, 'Čt':0, 'Pá':0, 'So':0, 'Ne':0}

for date in unique_calls_df['dateTimeOrigination']:
    if pd.notna(date):
        den = date.weekday()  # pondělí=0, neděle=6
        if den == 0:
            dni['Po'] += 1
        elif den == 1:
            dni['Út'] += 1
        elif den == 2:
            dni['St'] += 1
        elif den == 3:
            dni['Čt'] += 1
        elif den == 4:
            dni['Pá'] += 1
        elif den == 5:
            dni['So'] += 1
        elif den == 6:
            dni['Ne'] += 1

print("Počet hovorů podle dnů v týdnu:")
for den, pocet in dni.items():
    print(f"{den}: {pocet}")

nazvy_dnu = list(dni.keys())
pocet_hovoru = list(dni.values())


plt.figure(figsize=(8,5))
plt.bar(nazvy_dnu, pocet_hovoru, color='skyblue', edgecolor='black')
plt.title('Počet hovorů podle dnů v týdnu')
plt.xlabel('Den v týdnu')
plt.ylabel('Počet hovorů')
plt.show()

In [ ]:
# Kdy se nejčastěji volá dle jednotlivých dnů 6-12, 12-18, 18-24 a 24-6
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])
casove_bloky = {'6-12':0, '12-18':0, '18-24':0, '0-6':0}

for date in unique_calls_df['dateTimeOrigination']:
    if pd.notna(date):
        hodina = date.hour
        if 6 <= hodina < 12:
            casove_bloky['6-12'] += 1
        elif 12 <= hodina < 18:
            casove_bloky['12-18'] += 1
        elif 18 <= hodina < 24:
            casove_bloky['18-24'] += 1
        else:  # 0-6
            casove_bloky['0-6'] += 1

print("Počet hovorů podle časových bloků:")
for blok, pocet in casove_bloky.items():
    print(f"{blok}: {pocet}")

nazvy_bloku = list(casove_bloky.keys())
pocet_hovoru = list(casove_bloky.values())

plt.figure(figsize=(8,5))
plt.bar(nazvy_bloku, pocet_hovoru, color='lightgreen', edgecolor='black')
plt.title('Počet hovorů podle časových bloků')
plt.xlabel('Časový blok')
plt.ylabel('Počet hovorů')
plt.show()

In [ ]:
unique_calls_df = df.drop_duplicates(subset=["globalCallID_callId", "origLegCallIdentifier"])
blok_4_20 = {4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 10:0, 11:0, 12:0, 13:0, 14:0, 15:0, 16:0, 17:0, 18:0, 19:0, 20:0}

for date in unique_calls_df['dateTimeOrigination']:
    if pd.notna(date):
        hodina = date.hour
        if 4 <= hodina < 20:
            blok_4_20[hodina] += 1


print("Distribuce hovorů v bloku 6-12 po hodinách:")
for hod, pocet in blok_4_20.items():
    print(f"{hod}:00 - {pocet} hovorů")


hodiny = list(blok_4_20.keys())
pocet_hovoru = list(blok_4_20.values())

plt.figure(figsize=(8,5))
plt.bar(hodiny, pocet_hovoru, color='skyblue', edgecolor='black')
plt.title('Distribuce hovorů v bloku 6-12 po hodinách')
plt.xlabel('Hodina')
plt.ylabel('Počet hovorů')
plt.xticks(hodiny) 
plt.show()