In [1]:
#Čištění dat
import pandas as pd
import pickle

In [2]:
data = pd.read_csv(r"C:\Users\adamk\Desktop\Digitální akademie DATA\Projekt\skript_02\cdr_files_chosen_columns.csv", header=[0, 1])

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\adamk\\Desktop\\Digitální akademie DATA\\Projekt\\skript_02\\cdr_files_chosen_columns.csv'

In [ ]:
#odstranění víceřádkého záhlaví
data.columns = data.columns.get_level_values(0)

In [ ]:
data.head()

,Unnamed: 0_level_0,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,0,1,16615182,19957562,1704072013,437734693017,16,19957563,4344124999,4344124999,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,1,16615183,19957564,1704078480,436618449646,16,19957565,433738509500050,433738509500050,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,2,1,16615184,19957566,1704085667,436359992566,16,19957567,433738509500050,433738509500050,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,3,1,16615185,19957568,1704087689,9999,16,19957569,4314014190122,4314014190122,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,4,1,16615186,19957570,1704089234,433496903750,0,19957571,4373935601800,4373935601800,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [ ]:
#odstranění sloupce s indexem, který pandas přidal při ukládání do CSV
data.drop(data.columns[0], axis=1, inplace=True)

In [ ]:
data.head()

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,1704072013,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,1704078480,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,1704085667,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,1704087689,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,1704089234,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [ ]:
data.dtypes

globalCallID_callManagerId            int64
globalCallID_callId                   int64
origLegCallIdentifier                 int64
dateTimeOrigination                   int64
callingPartyNumber                   object
origCause_value                       int64
destLegIdentifier                     int64
originalCalledPartyNumber            object
finalCalledPartyNumber               object
destCause_value                       int64
dateTimeConnect                       int64
dateTimeDisconnect                    int64
lastRedirectDn                       object
pkid                                 object
duration                              int64
origDeviceName                       object
destDeviceName                       object
origCallTerminationOnBehalfOf         int64
destCallTerminationOnBehalfOf         int64
origCalledPartyRedirectOnBehalfOf     int64
lastRedirectRedirectOnBehalfOf        int64
origCalledPartyRedirectReason         int64
lastRedirectRedirectReason            int64
joinOnBehalfOf                        int64
callSecuredStatus                     int64
dtype: object

In [ ]:
#převod telefonních čísel na string
for sloupec in ['callingPartyNumber', 'originalCalledPartyNumber', 'finalCalledPartyNumber']:
    data[sloupec] = data[sloupec].astype(str)

In [ ]:
# Oprava telefonních čísel - jsou různě dlouhá, nahrazujeme + za 00(Zbytek ignorujeme - telefonní čísla jsou různě dlouhá a v různých zápisech)
def uprav_cislo(number):
    number = str(number).strip()
    if number.startswith('+'):
        number = '00' + number[1:]
    return number

In [ ]:
phone_columns = ['callingPartyNumber', 'originalCalledPartyNumber', 'finalCalledPartyNumber']

for column in phone_columns:
    data[column] = data[column].apply(uprav_cislo)

In [ ]:
data.head()

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [ ]:
#Převod Unix timestamp sloupců na datetime
casove_sloupce = ['dateTimeOrigination', 'dateTimeConnect', 'dateTimeDisconnect']
for sloupec in casove_sloupce:
    data[sloupec] = pd.to_datetime(data[sloupec], unit='s')

In [ ]:
for sloupec in casove_sloupce:
    data[sloupec] = data[sloupec].replace(pd.Timestamp('1970-01-01 00:00:00'), pd.NaT) # NaT = Not a Time
print(data[casove_sloupce])

        dateTimeOrigination     dateTimeConnect  dateTimeDisconnect
0       2024-01-01 01:20:13 2024-01-01 01:20:14 2024-01-01 01:20:22
1       2024-01-01 03:08:00 2024-01-01 03:08:02 2024-01-01 03:08:14
2       2024-01-01 05:07:47                 NaT 2024-01-01 05:07:47
3       2024-01-01 05:41:29 2024-01-01 05:41:31 2024-01-01 05:42:05
4       2024-01-01 06:07:14 2024-01-01 06:07:15 2024-01-01 06:07:50
...                     ...                 ...                 ...
3805581 2024-03-29 19:15:54 2024-03-29 19:15:54 2024-03-29 19:16:39
3805582 2024-03-30 15:12:29 2024-03-30 15:12:42 2024-03-30 15:29:03
3805583 2024-03-30 15:34:07 2024-03-30 15:34:31 2024-03-30 16:06:17
3805584 2024-03-30 18:13:14 2024-03-30 18:13:31 2024-03-30 18:14:02
3805585 2024-03-31 10:04:59                 NaT 2024-03-31 10:05:15

[3805586 rows x 3 columns]

In [ ]:
data.head()

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [ ]:
data.dtypes

globalCallID_callManagerId                    int64
globalCallID_callId                           int64
origLegCallIdentifier                         int64
dateTimeOrigination                  datetime64[ns]
callingPartyNumber                   string[python]
origCause_value                               int64
destLegIdentifier                             int64
originalCalledPartyNumber            string[python]
finalCalledPartyNumber               string[python]
destCause_value                               int64
dateTimeConnect                      datetime64[ns]
dateTimeDisconnect                   datetime64[ns]
lastRedirectDn                       string[python]
pkid                                 string[python]
duration                                      int64
origDeviceName                       string[python]
destDeviceName                       string[python]
origCallTerminationOnBehalfOf                 int64
destCallTerminationOnBehalfOf                 int64
origCalledPartyRedirectOnBehalfOf             int64
lastRedirectRedirectOnBehalfOf                int64
origCalledPartyRedirectReason                 int64
lastRedirectRedirectReason                    int64
joinOnBehalfOf                                int64
callSecuredStatus                             int64
dtype: object

In [ ]:
#převod na stringy
for sloupec1 in ['callingPartyNumber', 'originalCalledPartyNumber', 'finalCalledPartyNumber']:
    data[sloupec1] = data[sloupec1].astype('string')


for sloupec2 in ['lastRedirectDn', 'pkid', 'origDeviceName', 'destDeviceName']:
    data[sloupec2] = data[sloupec2].astype('string')

In [ ]:
data.dtypes

globalCallID_callManagerId                    int64
globalCallID_callId                           int64
origLegCallIdentifier                         int64
dateTimeOrigination                  datetime64[ns]
callingPartyNumber                   string[python]
origCause_value                               int64
destLegIdentifier                             int64
originalCalledPartyNumber            string[python]
finalCalledPartyNumber               string[python]
destCause_value                               int64
dateTimeConnect                      datetime64[ns]
dateTimeDisconnect                   datetime64[ns]
lastRedirectDn                       string[python]
pkid                                 string[python]
duration                                      int64
origDeviceName                       string[python]
destDeviceName                       string[python]
origCallTerminationOnBehalfOf                 int64
destCallTerminationOnBehalfOf                 int64
origCalledPartyRedirectOnBehalfOf             int64
lastRedirectRedirectOnBehalfOf                int64
origCalledPartyRedirectReason                 int64
lastRedirectRedirectReason                    int64
joinOnBehalfOf                                int64
callSecuredStatus                             int64
dtype: object

In [ ]:
data.to_pickle(r"C:\Users\adamk\Desktop\Digitální akademie DATA\Projekt\skript_02\cdr_files_clean.pkl") #pickle pro uložení datových typů

In [ ]:
data.head()

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [ ]:
data['duration'].head()

0     8
1    12
2     0
3    34
4    35
Name: duration, dtype: int64

In [ ]:
#přidání jednotky k názvu sloupce duration
data.rename(columns={'duration': 'duration (sekundy)'})

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3805581,4,6319773,68494904,2024-03-29 19:15:54,43204838804831,0,68494909,43204838804829,5058900,16,...,SEP7429F87079C2,Unity_Connection_Publisher,1,12,5,1,178,18,1,0
3805582,4,6319775,68495018,2024-03-30 15:12:29,434005336339264,16,68495019,50335447441930,50335447441930,0,...,TCTR53C1264,BK053_079_Tele2,12,0,0,0,0,0,0,0
3805583,4,6319776,68495025,2024-03-30 15:34:07,434005336339264,16,68495026,50335447441930,50335447441930,0,...,TCTR53C1264,BK053_079_Tele2,12,0,0,0,0,0,0,0
3805584,4,6319777,68495037,2024-03-30 18:13:14,432537661412,0,68495038,2868767180,2868767180,16,...,CSFC29KJDI,BK044_000_Tele2,0,12,0,0,0,0,0,0
3805585,4,6319778,68495119,2024-03-31 10:04:59,434424270388476,16,68495120,92854133396,92854133396,0,...,SEP7429F8708F4A,BK044_058_Tele2,12,0,0,0,0,0,0,0

In [ ]:
#POZOR: JEDEN ŘÁDEK NEROVNÁ SE JEDEN HOVOR. Jeden hovor může být i na více řádků.
data['duration'].describe().round(1)

count    3805586.0
mean          88.4
std          257.2
min            0.0
25%            0.0
50%           15.0
75%           84.0
max        43200.0
Name: duration, dtype: float64

In [ ]:
print("Pocet radku a sloupcu:", data.shape)
data.dtypes

Pocet radku a sloupcu: (3805586, 25)

globalCallID_callManagerId                    int64
globalCallID_callId                           int64
origLegCallIdentifier                         int64
dateTimeOrigination                  datetime64[ns]
callingPartyNumber                   string[python]
origCause_value                               int64
destLegIdentifier                             int64
originalCalledPartyNumber            string[python]
finalCalledPartyNumber               string[python]
destCause_value                               int64
dateTimeConnect                      datetime64[ns]
dateTimeDisconnect                   datetime64[ns]
lastRedirectDn                       string[python]
pkid                                 string[python]
duration                                      int64
origDeviceName                       string[python]
destDeviceName                       string[python]
origCallTerminationOnBehalfOf                 int64
destCallTerminationOnBehalfOf                 int64
origCalledPartyRedirectOnBehalfOf             int64
lastRedirectRedirectOnBehalfOf                int64
origCalledPartyRedirectReason                 int64
lastRedirectRedirectReason                    int64
joinOnBehalfOf                                int64
callSecuredStatus                             int64
dtype: object

In [ ]:
print("\nPocet chybejicich NaN hodnot:")
data.isna().sum() #jiné než vyšlo Lucce

Pocet chybejicich NaN hodnot:

globalCallID_callManagerId                0
globalCallID_callId                       0
origLegCallIdentifier                     0
dateTimeOrigination                       2
callingPartyNumber                        0
origCause_value                           0
destLegIdentifier                         0
originalCalledPartyNumber                 0
finalCalledPartyNumber                    0
destCause_value                           0
dateTimeConnect                      557165
dateTimeDisconnect                        0
lastRedirectDn                       603095
pkid                                      0
duration                                  0
origDeviceName                       549251
destDeviceName                       160135
origCallTerminationOnBehalfOf             0
destCallTerminationOnBehalfOf             0
origCalledPartyRedirectOnBehalfOf         0
lastRedirectRedirectOnBehalfOf            0
origCalledPartyRedirectReason             0
lastRedirectRedirectReason                0
joinOnBehalfOf                            0
callSecuredStatus                         0
dtype: int64

In [ ]:
data[["dateTimeOrigination", "dateTimeConnect", "dateTimeDisconnect"]].head()

  dateTimeOrigination     dateTimeConnect  dateTimeDisconnect
0 2024-01-01 01:20:13 2024-01-01 01:20:14 2024-01-01 01:20:22
1 2024-01-01 03:08:00 2024-01-01 03:08:02 2024-01-01 03:08:14
2 2024-01-01 05:07:47                 NaT 2024-01-01 05:07:47
3 2024-01-01 05:41:29 2024-01-01 05:41:31 2024-01-01 05:42:05
4 2024-01-01 06:07:14 2024-01-01 06:07:15 2024-01-01 06:07:50

In [ ]:
unique_calls = (
    data.groupby(["globalCallID_callId", "globalCallID_callManagerId","dateTimeOrigination"])
    .ngroups
)
print(f"skutecny pocet unikatnich hovoru: {unique_calls}")

skutecny pocet unikatnich hovoru: 3299854

In [ ]:
print("celkovy pocet radku:", len(data))
print("Skutecny pocet hovoru:", unique_calls)
print("Pocet duplicitnich zaznamu:", len(data) - unique_calls)

celkovy pocet radku: 3805586
Skutecny pocet hovoru: 3299854
Pocet duplicitnich zaznamu: 505732

In [ ]:
data.to_pickle(r"C:\Users\adamk\Desktop\Digitální akademie DATA\Projekt\skript_02\cdr_files_clean.pkl") #pickle pro uložení datových typů

In [ ]:
data.dtypes

globalCallID_callManagerId                    int64
globalCallID_callId                           int64
origLegCallIdentifier                         int64
dateTimeOrigination                  datetime64[ns]
callingPartyNumber                   string[python]
origCause_value                               int64
destLegIdentifier                             int64
originalCalledPartyNumber            string[python]
finalCalledPartyNumber               string[python]
destCause_value                               int64
dateTimeConnect                      datetime64[ns]
dateTimeDisconnect                   datetime64[ns]
lastRedirectDn                       string[python]
pkid                                 string[python]
duration                                      int64
origDeviceName                       string[python]
destDeviceName                       string[python]
origCallTerminationOnBehalfOf                 int64
destCallTerminationOnBehalfOf                 int64
origCalledPartyRedirectOnBehalfOf             int64
lastRedirectRedirectOnBehalfOf                int64
origCalledPartyRedirectReason                 int64
lastRedirectRedirectReason                    int64
joinOnBehalfOf                                int64
callSecuredStatus                             int64
dtype: object